apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: test-taskrun
  namespace: tekton-pipelines
spec:
  serviceAccountName: pipeline
  taskSpec:
    params:
    - name: buildRevision
    - name: appGitUrl
    workspaces:
    - name: app-source

    steps:
    - name: git-checkout
      image: alpine/git:v2.26.2
      workingDir: "$(workspaces.app-source.path)"
      script: |
        #!/usr/bin/env sh
        set -e

        eval $(ssh-agent)
        ssh-add ~/.ssh/id_*
        git config --global core.sshCommand 'ssh -o StrictHostKeyChecking=accept-new'

        git init
        git remote add origin $(params.appGitUrl)
        git fetch --depth 1 origin $(params.buildRevision)
        git checkout FETCH_HEAD

    - name: build-sources
      image: sdaschner/maven-jdk14:quarkus-deps-1.5.1-b5
      workingDir: "$(workspaces.app-source.path)/coffee-shop"
      command: ["sleep", "infinity"]

      # specify other specs, like in the regular task definitions

#      env:
#      - name: MAVEN_OPTS
#        value: "-X..."

  params:
  - name: buildRevision
    value: '56512b4a01fc91026b0d42ba2febb1b61c291903'
  - name: appGitUrl
    value: 'git@github.com:sdaschner/coffee-testing.git'
  workspaces:
  - name: app-source
    emptyDir: {}
---